AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Leave approval workflow (API Gateway + Step Functions)

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 10
    MemorySize: 128

Parameters:
  JwtSecret:
    Type: String
    NoEcho: true
    Description: Secret key for JWT authorizer

Resources:
  LeaveApprovalStateMachineSouvik:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      DefinitionUri: statemachine/leave-workflow.asl.json
      Policies:
        - LambdaInvokePolicy:
            FunctionName: '*'

  LeaveApiSouvik:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
      DefinitionBody:
        openapi: '3.0.1'
        info:
          title: Leave API Souvik
          version: '1.0'
        paths:
          /leave/request:
            post:
              security:
                - LambdaAuthorizer: []
              responses:
                '200':
                  description: Accepted
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri: !Sub arn:aws:apigateway:${AWS::Region}:states:action/StartExecution
                credentials: !GetAtt ApiGatewayStepFunctionRoleSouvik.Arn
                requestTemplates:
                  application/json: !Sub |
                    {
                      "stateMachineArn": "${LeaveApprovalStateMachineSouvik}",
                      "input": "$util.escapeJavaScript($input.body)"
                    }
                responses:
                  '200':
                    statusCode: 200
                    responseTemplates:
                      application/json: |
                        {
                          "success": true,
                          "message": "Leave request submitted successfully",
                        }
          /leave/decision:
            get:
              parameters:
                - name: token
                  in: query
                  required: true
                  schema:
                    type: string
                - name: status
                  in: query
                  required: true
                  schema:
                    type: string
                    enum: [APPROVED, REJECTED]
              responses:
                '200':
                  description: Decision accepted
              x-amazon-apigateway-integration:
                type: aws_proxy
                httpMethod: POST
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResumeApprovalFunctionSouvik.Arn}/invocations
        securityDefinitions:
          LambdaAuthorizer:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: custom
            x-amazon-apigateway-authorizer:
              type: token
              authorizerUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JwtLeaveTrackerFunctionSouvik.Arn}/invocations
              authorizerResultTtlInSeconds: 1

  JwtLeaveTrackerFunctionSouvik:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs24.x
      Handler: authorizer.handler
      CodeUri: ./
      Environment:
        Variables:
          JWT_SECRET: !Ref JwtSecret
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        External:
          - '@aws-sdk/*'
        EntryPoints:
          - src/auth/authorizer.ts

  SendApprovalEmailFunctionSouvik:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: send-approval-email-souvik
      Handler: sendApprovalEmail.handler
      CodeUri: ./
      Environment:
        Variables:
          SOURCE_EMAIL: souvik.biswas@antstack.io
          APPROVER_EMAIL: biswassouvik284@gmail.com
          DECISION_API_BASE_URL: !Sub https://${LeaveApiSouvik}.execute-api.${AWS::Region}.amazonaws.com/test/leave/decision
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendTemplatedEmail
            Resource: '*'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        External:
          - '@aws-sdk/*'
        EntryPoints:
          - src/functions/sendApprovalEmail.ts

  ResumeApprovalFunctionSouvik:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: resume-approval-souvik
      Handler: resumeApproval.handler
      CodeUri: ./
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - states:SendTaskSuccess
              - states:SendTaskFailure
            Resource: '*'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        External:
          - '@aws-sdk/*'
        EntryPoints:
          - src/functions/resumeApproval.ts

  JwtLeaveTrackerFunctionSouvikLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${JwtLeaveTrackerFunctionSouvik}
      RetentionInDays: 14

  SendApprovalEmailFunctionSouvikLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${SendApprovalEmailFunctionSouvik}
      RetentionInDays: 14

  ResumeApprovalFunctionSouvikLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${ResumeApprovalFunctionSouvik}
      RetentionInDays: 14

  NotifyUserFunctionSouvikLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${NotifyUserFunctionSouvik}
      RetentionInDays: 14
  NotifyUserFunctionSouvik:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: notify-user-souvik
      Handler: notifyUser.handler
      CodeUri: ./
      Environment:
        Variables:
          SOURCE_EMAIL: souvik.biswas@antstack.io
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendTemplatedEmail
            Resource: '*'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        External:
          - '@aws-sdk/*'
        EntryPoints:
          - src/functions/notifyUser.ts

  ApiGatewayStepFunctionRoleSouvik:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ApiGatewayStartStepFunction
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref LeaveApprovalStateMachineSouvik

  JwtAuthorizerInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref JwtLeaveTrackerFunctionSouvik
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${LeaveApiSouvik}/*

  ApproveLeaveFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResumeApprovalFunctionSouvik
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${LeaveApiSouvik}/*/*

  LeaveApprovalRequestTemplateSouvik:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: LeaveApprovalRequestSouvik
        SubjectPart: Leave approval required
        TextPart: |
          A leave request requires your approval.

          Employee: {{employeeEmail}}
          From: {{fromDate}}
          To: {{toDate}}
          Reason: {{reason}}

          Approve: {{approveLink}}
          Reject: {{rejectLink}}

          This request expires in 3 days.
        HtmlPart: |
          <p>A leave request requires your approval.</p>
          <p>
            <strong>Employee:</strong> {{employeeEmail}}<br/>
            <strong>From:</strong> {{fromDate}}<br/>
            <strong>To:</strong> {{toDate}}<br/>
            <strong>Reason:</strong> {{reason}}
          </p>
          <a href="{{approveLink}}">Approve</a> |
          <a href="{{rejectLink}}">Reject</a>

  LeaveDecisionNotificationTemplateSouvik:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: LeaveDecisionNotificationSouvik
        SubjectPart: Leave request {{status}}
        TextPart: |
          Your leave request has been {{status}}.
          From: {{fromDate}}
          To: {{toDate}}
          {{message}}
        HtmlPart: |
          <p>Your leave request has been <strong>{{status}}</strong>.</p>

  ResumeApprovalLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ResumeApprovalFunctionSouvik
      Principal: apigateway.amazonaws.com
